GET http://localhost:3002/api/persons

###
DELETE http://localhost:3002/api/persons/3


###
POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Agustin",
    "number": 323453
}